name = "jiwonz/luau_check"
version = "0.3.13"
description = "Check and lint your luau project with recommended toolings such as selene, luau-lsp, and stylua"
authors = ["jiwonz <me@jiwonz.kr>"]
license = "MIT"
repository = "https://github.com/jiwonz/luau_check.git"
includes = ["README.md", "LICENSE", "bin.luau", "pesde.toml"]

[target]
environment = "lune"
bin = "bin.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[engines]
lune = "^0.8.9"
pesde = "^0.6.2"

[peer_dependencies]
selene = { name = "pesde/selene", version = "*" }
luau_lsp = { name = "pesde/luau_lsp", version = "*" }
stylua = { name = "pesde/stylua", version = "*" }

[dependencies]
pathfs = { name = "jiwonz/pathfs", version = "^0.6.0-rc.2" }
dirs = { name = "jiwonz/dirs", version = "^0.4.0" }
pesde_exec = { name = "jiwonz/pesde_exec", version = "^0.4.2" }
