name = "jiwonz/luau_check"
version = "0.3.2"
description = "Check and lint your luau project with recommended toolings such as selene, luau-lsp, and stylua"
authors = ["jiwonz <me@jiwonz.kr>"]
license = "MIT"
repository = "https://github.com/jiwonz/luau_check.git"
includes = ["README.md", "LICENSE", "bin.luau", "pesde.toml"]

[target]
environment = "lune"
bin = "bin.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[peer_dependencies]
selene = { name = "pesde/selene", version = "^0.28.0" }
luau_lsp = { name = "pesde/luau_lsp", version = "^1.37.0" }
stylua = { name = "pesde/stylua", version = "^2.0.2" }

[dependencies]
pathfs = { name = "jiwonz/pathfs", version = "^0.5.0" }
dirs = { name = "jiwonz/dirs", version = "^0.3.0" }
pesde_exec = { name = "jiwonz/pesde_exec", version = "^0.3.0" }
